// ============================================
// XEROVA — Report Export API (PDF/MD/JSON)
// ============================================

import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { connectDB } from "@/lib/db";
import Report from "@/models/Report";
import { IReportDocument } from "@/models/Report";

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id } = await params;
    const { searchParams } = new URL(request.url);
    const format = searchParams.get("format") || "json";

    await connectDB();

    const report = (await Report.findOne({
      _id: id,
      userId: session.user.id,
    }).lean()) as IReportDocument | null;

    if (!report) {
      return NextResponse.json({ error: "Report not found" }, { status: 404 });
    }

    if (format === "json") {
      return NextResponse.json(report);
    }

    if (format === "markdown" || format === "md") {
      const md = generateMarkdown(report);
      return new NextResponse(md, {
        headers: {
          "Content-Type": "text/markdown",
          "Content-Disposition": `attachment; filename="XEROVA_Report_${report._id}.md"`,
        },
      });
    }

    if (format === "pdf") {
      // NOTE: We rely on the client for actual PDF generation via @react-pdf/renderer
      // The API just tells the client it's not supported via direct GET stream here
      return NextResponse.json(
        { error: "PDF generation should be handled client-side using @react-pdf/renderer" },
        { status: 400 }
      );
    }

    return NextResponse.json(
      { error: "Invalid format requested. Use json or md." },
      { status: 400 }
    );
  } catch (error) {
    console.error("[Report Export Error]:", error);
    return NextResponse.json(
      { error: "Failed to export report" },
      { status: 500 }
    );
  }
}

function generateMarkdown(report: IReportDocument): string {
  let md = `# XEROVA Intelligence Report\n\n`;
  md += `**Title**: ${report.title}\n`;
  md += `**Type**: ${report.type.toUpperCase()}\n`;
  md += `**Date**: ${new Date(report.createdAt).toUTCString()}\n`;
  md += `**Risk Score**: ${report.riskScore}/100\n\n`;
  md += `---\n\n`;

  if (report.summary) {
    md += `## Summary\n\n${report.summary}\n\n`;
  }

  if (report.iocs && report.iocs.length > 0) {
    md += `## Indicators of Compromise (IOCs)\n\n`;
    report.iocs.forEach((ioc) => {
      md += `- **${ioc.type.toUpperCase()}**: \`${ioc.value}\``;
      if (ioc.context) md += ` — ${ioc.context}`;
      md += `\n`;
    });
    md += `\n`;
  }

  if (report.findings && report.findings.length > 0) {
    md += `## Findings\n\n`;
    report.findings.forEach((finding, i) => {
      md += `### ${i + 1}. ${finding.title}\n`;
      md += `**Severity**: ${finding.severity.toUpperCase()}\n\n`;
      md += `${finding.description}\n\n`;
      if (finding.evidence) {
        md += `**Evidence**:\n\`\`\`text\n${finding.evidence}\n\`\`\`\n\n`;
      }
    });
  }

  md += `---\n*Generated by XEROVA Cybersecurity Platform*`;
  return md;
}
